apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0JIM0RjZHI2Y2xsbGI1RU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalF4TWpFMU1USXpOakV4V2hjTk16UXhNakUxTVRJegpOakV4V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBNlRHSFVQSEhSdjAvbWVJelVTdjUyWGtXazQ0dCtsVHFGY2czYUhvUUI1V3AKcHlEWnRycVJaS0pGWDhyalpDenNlNXhwaS90bDJDS3lFMkRMSmEvNzVleDZPcndQeW5tMi9QaW0vWlJTekZOYQpqSS9GNXQrb3hVMzl3ZlRPNmFDQytPU25kQnRTbTJNYjNHOU4zcTF2d1gvWkV6aW0yUUlMaVdKdG5XRDQ3WHpZClBCRUx2MW5ONUw5MzBiNXZRRWJuU2gwZHRQTkFMaTVOQ2czLzNyUHNEbU5jK2RoMW1BZVdqWGQrVjhjYUpxeEQKeE1FdURJYTVtd2Rtb1JyOGhxc0psVFNmck91VWJxelAxeXdMZmx0Z0hRVFVxRTNpUU85b0tVbWorWCs0T0FPVgpvNk9qMVJzaURRZzVGUVNHTkRYcU9IVHZJbWxwSnp6aDd1d3FQWm9NYVFJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVJrUXNDb0NkcEF5Ly8vcDIKNG83Z2JJS1o4VmN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVNM2cvWGQrQ1Z2emRuRG8ydDJZNGY2TElidgpBWll4ZDdWSmFQNCtsSjN1QStPSk51ZHBZNHZMZFY2TDZFNk9lRnhERUVlWkl5U2RoVmlGVGo3NGVsNEZPMWdGCnBSR1k2dFRxdGp3STFzTno5ZHdRMmFyNkpBT1Z1bHF4VGVGZWJuYkFDTENGTzBGYzFWU0w2QWlSeUszVVhRMkUKZmpGd2RjdGMreVJzQkV5QlBxYlVEMVlhR2dneXlyT1RHeHJvUG1QWkJFYWhSc3FLZFhpNHlmVTAwWUswempIaApSRk5ObVRtYzN3VEwxOWJOVjdHalN6TFI5c3pOVDFIc3J0SC9rdTAvTUJraWNzb1ZBNkthbVRKellrSHN4eXFXCm5TbGc2RDJzMnFXMEp5QzNrK2l5VW05L0EyU2hibG5xeXFZQWpWb0RCL3lvMmRvM1FsNmJxQkZQR1dRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.vineethbk.xyz
    tls-server-name: api.internal.vineethbk.xyz
  name: vineethbk.xyz
contexts:
- context:
    cluster: vineethbk.xyz
    namespace: production
    user: user2
  name: user2-context
current-context: user2-context
kind: Config
users:
- name: user2
  user:
    client-certificate: /root/user2.crt
    client-key: /root/user2.key
